### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by TomTasche** [clinejj/foursquare-api-java#1]
(I'm creating an issue here because the fork that's linked from the official Foursquare API docs has issues disabled)

i tried to integrate your library into an Android project (because according to some articles this library is compatible with Android) but I'm not able to compile the app: "trouble writing output: Too many method references: 76856; max is 65536"

this is because your library includes the appengine SDK, which seems to be fairly huge. do you really depend on the appengine SDK or is there a way to exclude it?

**Comment by ceefour** [comment]
#13 fixed this issue. please merge. GAE users will have to add this dependency exactly as described in the wiki https://github.com/clinejj/foursquare-api-java/wiki/Maven but intuitively, GAE users will already have that dependency anyway
